// export const carBrands = [
//   "Acura",
//   "Alfa Romeo",
//   "Aston Martin",
//   "Audi",
//   "Bentley",
//   "BMW",
//   "Bugatti",
//   "Buick",
//   "Cadillac",
//   "Chevrolet",
//   "Chrysler",
//   "Citroen",
//   "Dodge",
//   "Ferrari",
//   "FIAT",
//   "Ford",
//   "GMC",
//   "Genesis",
//   "Honda",
//   "Hyundai",
//   "Infiniti",
//   "Jaguar",
//   "Jeep",
//   "Kia",
//   "Koenigsegg",
//   "Lamborghini",
//   "Land Rover",
//   "Lexus",
//   "Lincoln",
//   "Lotus",
//   "Maserati",
//   "Mazda",
//   "McLaren",
//   "Mercedes-Benz",
//   "MINI",
//   "Mitsubishi",
//   "Nissan",
//   "Porsche",
//   "Ram",
//   "Rolls-Royce",
//   "Scion",
//   "Smart",
//   "Subaru",
//   "Suzuki",
//   "Tesla",
//   "Toyota",
//   "Volkswagen",
//   "Volvo",
// ];
export const jobCategories = [
  "Accounting",
  "Administration",
  "Art and Design",
  "Business Development",
  "Communications",
  "Customer Service",
  "Education",
  "Engineering",
  "Finance",
  "Healthcare",
  "Human Resources",
  "Information Technology",
  "Legal",
  "Management",
  "Marketing",
  "Media",
  "Operations",
  "Project Management",
  "Research",
  "Sales",
  "Science",
  "Social Services",
  "Sports and Fitness",
  "Transportation",
  "Writing and Editing",
];
export const WEB_TITLE = "Accessible Careers";
